name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read package information
        run: |
          $version = (Get-Content ./package.json) | ConvertFrom-Json | Select -ExpandProperty "version"
          $name = (Get-Content ./package.json) | ConvertFrom-Json | Select -ExpandProperty "name"
          "PACKAGE_NAME=$name-$version" >> $env:GITHUB_ENV

      - name: Install
        run: npm install
      
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Install VSCE
        run: npm install -g vsce

      - name: build
        run: vsce package

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}.vsix
          path: ./${{ env.PACKAGE_NAME }}.vsix
          retention-days: 5
