name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Install VSCE
        run: npm install -g vsce

      - name: Build
        run: vsce package
